### ISSUE TITLE
Setup jest in the project 

### ISSUE THREAD

**Issue by eerison** [Willian1661/calculate_project#2]
https://jestjs.io/docs/getting-started

**Comment by eerison** [comment]
Hey @Willian1661 what error are you facing?

**Comment by Willian1661** [comment]
I added the following section to my package.json:
{
  "scripts": {
    "test": "jest"
  }
}

and i got a "End of file expected.json"

**Comment by eerison** [comment]
> I added the following section to my package.json: { "scripts": { "test": "jest" } }
> 
> and i got a "End of file expected.json"

Hmmmm but it looks correct for me 🤔

**Comment by eerison** [comment]
Did you create this file manually or was it generated by npm?

**Comment by Willian1661** [comment]
was created by npm

**Comment by eerison** [comment]
> I added the following section to my package.json: { "scripts": { "test": "jest" } }
> 
> and i got a "End of file expected.json"

OK try do generate it again by npm, you don't need to add this test entry,  you can just add it as a dependency,  like the doc says 

https://jestjs.io/docs/getting-started

**Comment by eerison** [comment]
> > I added the following section to my package.json: { "scripts": { "test": "jest" } }
> > and i got a "End of file expected.json"
> 
> OK try do generate it again by npm, you don't need to add this test entry, you can just add it as a dependency, like the doc says
> 
> https://jestjs.io/docs/getting-started

Have you checked the first step in the doc?

**Comment by eerison** [comment]
Ahhh I see, you are right! The docs recommend you to add 

```json
{
  "scripts": {
    "test": "jest"
  }
}
```

But your file just have this, it's not correct

**Comment by eerison** [comment]
> I added the following section to my package.json: { "scripts": { "test": "jest" } }
> 
> and i got a "End of file expected.json"

It's missing the jest in your dependency list,  try to generate this file again using npm,  it will be fixed automatically

**Comment by Willian1661** [comment]
by default the npm create two packges, one **package-lock.json** and one **package.json**.
it says to add that section to the second one.
it only have the devDependencies at first: 

{
  "devDependencies": {
    "jest": "^29.3.1"
  }
}

**Comment by Willian1661** [comment]
when i add the section
{
  "scripts": {
    "test": "jest"
  }
}
i got an error "End of file expected.json"

**Comment by eerison** [comment]
> by default the npm create two packges, one **package-lock.json** and one **package.json**. it says to add that section to the second one. it only have the devDependencies at first:
> 
> { "devDependencies": { "jest": "^29.3.1" } }

Cool,  now you add the script line into the file, you were replacing the whole file 🤭

**Comment by eerison** [comment]
> when i add the section { "scripts": { "test": "jest" } } i got an error "End of file expected.json"

After you add the script line, please post here

**Comment by eerison** [comment]
And could you use json format in your comment,  it's better to read your code :)

**Comment by eerison** [comment]
For example https://stackoverflow.com/questions/14901245/how-to-style-a-json-block-in-github-wiki

**Comment by Willian1661** [comment]
i added the section correctly (i think):
{
   "devDependencies": {
      "jest": "^29.3.1"
   },
   "scripts": {
      "test": "jest"
   }
}

and i ran the  "npm test"/ "npm run test" and i get a 

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0

  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 3 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches

**Comment by eerison** [comment]
> i added the section correctly (i think): { "devDependencies": { "jest": "^29.3.1" }, "scripts": { "test": "jest" } }
> 
> and i ran the "npm test"/ "npm run test" and i get a
> 
> No tests found, exiting with code 1 Run with `--passWithNoTests` to exit with code 0
> 
> testMatch: **/**tests**/**/_.[jt]s?(x), **/?(_.)+(spec|test).[tj]s?(x) - 0 matches testPathIgnorePatterns: /node_modules/ - 3 matches testRegex: - 0 matches Pattern: - 0 matches

Thatis correct,  you didn't create any test, try to add a simple test,  check in the docks

**Comment by eerison** [comment]
You can add a sum test like here

https://jestjs.io/docs/getting-started

**Comment by eerison** [comment]
@Willian1661 did you test it 👆?

**Comment by Willian1661** [comment]
@eerison yea i created the test, i have one file for the test and one file that it'll be tested**(sum.js and sum.test.js)**.
i did all the initial steps of the https://jestjs.io/docs/getting-started , that's the weird and still don't run.

**Comment by Willian1661** [comment]
I'm recapping everything again, because I still don't got it what went wrong :´)

**Comment by eerison** [comment]
Could you open a PR with your changes?

**Comment by Willian1661** [comment]
i can but not now.
i'am on class now, i'll do it later

**Comment by Willian1661** [comment]
@eerison it worked 🎆🎇
I was searching for one way to do this and found that I didn't  initialized the command line: **npm init -y** in the directory.
so i did it all over again and made the tests and it worked :)

**Comment by eerison** [comment]
> @eerison it worked 🎆🎇 I was searching for one way to do this and found that I didn't initialized the command line: **npm init -y** in the directory. so i did it all over again and made the tests and it worked :)

Nice 👏👏
Could you open the PR please

**Comment by Willian1661** [comment]
i'am going to try do it today, on this week i'm having extra classes in the estacio, this classes tooks my whole morning.
so i'am trying to change my routine to have more time to do this.
