### ISSUE TITLE
Add tests in pipelines

### ISSUE THREAD

**Issue by eerison** [Willian1661/calculate_project#4]
Docs: https://docs.github.com/en/actions/quickstart

it should run on `push` and `pull_request`

- [ ] Create a build step
- [ ] Create a test step

**Comment by eerison** [comment]
![Notes_221209_131037_1](https://user-images.githubusercontent.com/6358755/206700748-fb53ef8f-a798-43b9-9bcf-4d813dae6ed2.jpg)

It's the image that we used @Willian1661 :)

**Comment by Willian1661** [comment]
beautiful :)

**Comment by Willian1661** [comment]
have already merged the branches on the last issue, right?
i'm deleting my local test-jest(the branch i created for the PR) and i'm going to delete the remote one.
so i can delete and create other branch to complete a different issue, can i?

**Comment by eerison** [comment]
> have already merged the branches on the last issue, right? i'm deleting my local test-jest(the branch i created for the PR) and i'm going to delete the remote one. so i can delete and create other branch to complete a different issue, can i?

Yep
