### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by eerison** [Willian1661/calculate_project#9]
- [x] setup eslint 
- [x] add eslint in pipelines

**Comment by eerison** [comment]
@Willian1661 
when you require the review please move your ticket for review column

**Comment by eerison** [comment]
Please check the comments ;)

**Comment by Willian1661** [comment]
which one? here or pr's comments

**Comment by Willian1661** [comment]
and i moved the ticket to review, but it came back to in progress, was you?

**Comment by eerison** [comment]
> and i moved the ticket to review, but it came back to in progress, was you?

Yep
